### ISSUE TITLE
Volume does not working on stopped sounds.

### ISSUE THREAD

**Issue by Rollo-Liu** [adireddy/waud#8]
When you play a sound by `sound.play()` it will ignore its volume and play with volume 1.0. The volume will only change when `sound.isPlaying()` is true and calling `sound.setVolume(blah)`.

With `sound.getVolume()` you can still get the volume value, but the playback just ignoring it.

Currently happing on Web Audio API. Not been tested on HTML5.

I tried on latest Chrome, Edge and Firefox. All acting the same.

**Comment by adireddy** [comment]
Can you git it a try and update here pls. v0.4.7

**Comment by Rollo-Liu** [comment]
Thanks for the quick fix Adi! The volume works now!

Cheers!

**Comment by adireddy** [comment]
:+1:
