### ISSUE TITLE
getTime() always returns 0

### ISSUE THREAD

**Issue by nealR** [adireddy/waud#9]
I've noticed in my scene that `IWaudSound.getTime()` always returns 0.

In your sample scene, you have
```javascript
_addButton("Seek", 300, 300, 60, 30, function() { _countdown.setTime(_countdown.getTime() + 1); });
```
But no matter how many times you press the seek button for countdown, it always starts from "1" because it's forever doing `_countdown.setTime(0 + 1);`

**Comment by nealR** [comment]
Sorry, just been informed that Waud currently doesn't support 'seek' so ignore this

**Comment by adireddy** [comment]
@nealR In the latest version the purpose of `setTime` is to enable seek functionality

I have only added this yesterday so could be buggy.

I could not reproduce the issue you mentioned above.

Which browser are you using to test?

**Comment by adireddy** [comment]
`getTime()` only returns the current playing time if the sound is playing else it will be 0.

In the sample, once you start playing the sound you can seek by 1 sec using seek button.

**Comment by nealR** [comment]
Using Chrome.

Ok so I didn't know that you can only seek while playing. However in your example, if you seek and then play countdown, it starts the countdown from "one". The sound was not playing, yet you were able to seek. Also, no matter how many times you hit seek, the countdown starts from "1" rather than "0".

However in my scene when I use seek, the sound always starts from "0". I have a 3 second long audio file, I first _sound.seek(1.5) and then _sound.play(), but the sound will still start from the beginning.

_native_sound is of type IWaudSound

```javascript
//Sets the playhead of the sound to a certain position (milliseconds)
public function seek(value:Float):Void
{
	value /= 1000;
	_native_Sound.setTime(value);
}

public function play():Void
{
	var wasProblem:Bool = false;
	try
	{
		_native_Sound.play();
	}
	catch(err:Dynamic)
	{
		wasProblem = true;
		Logger.warning(this, 'Error while playing "$_name" from $_path');
	}
}

**Comment by adireddy** [comment]
You don't need to play the sound before seek. It's a bug and I just fixed it. With this fix you should be able to call `setTime` first and play later.

Just added another sample to test the same 😄 

http://adireddy.github.io/demos/waud/sample2.html
